<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Rental Agreement</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; line-height: 1.6; }
        h1 { color: #4a3f6b; font-size: 20px; margin-bottom: 4px; }
        h2 { color: #4a3f6b; font-size: 14px; margin-top: 20px; }
        .meta { color: #666; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin: 12px 0; }
        td { padding: 6px 8px; border: 1px solid #ddd; vertical-align: top; }
        td.label { background: #f5f3ff; font-weight: bold; width: 35%; }
        .footer { margin-top: 40px; font-size: 10px; color: #888; }
    </style>
</head>
<body>
    <h1>Rental Agreement</h1>
    <p class="meta">Generated {{ now()->format('F j, Y') }} · Booking #{{ $booking->id }}</p>

    <h2>Parties</h2>
    <table>
        <tr><td class="label">Landlord</td><td>{{ $landlord->business_name ?? $landlord->user->name }}<br>{{ $landlord->phone ?? 'N/A' }}</td></tr>
        <tr><td class="label">Tenant</td><td>{{ $tenant->name }}<br>{{ $tenant->email }}</td></tr>
    </table>

    <h2>Property & Room</h2>
    <table>
        <tr><td class="label">Property</td><td>{{ $property->name }}</td></tr>
        <tr><td class="label">Address</td><td>{{ $property->address }}, {{ $property->city }}</td></tr>
        <tr><td class="label">Room</td><td>{{ $room->name }} ({{ $room->typeLabel() }})</td></tr>
        <tr><td class="label">Monthly Rent</td><td>${{ number_format($room->price, 2) }}</td></tr>
    </table>

    <h2>Term</h2>
    <table>
        <tr><td class="label">Move-in Date</td><td>{{ $booking->move_in_date?->format('F j, Y') }}</td></tr>
        <tr><td class="label">Duration</td><td>{{ $booking->duration_months }} month(s)</td></tr>
    </table>

    <h2>Terms & Conditions</h2>
    <ol>
        <li>Tenant agrees to pay rent monthly in advance on or before the move-in anniversary date.</li>
        <li>Tenant shall maintain the room in good condition and comply with house rules.</li>
        <li>Landlord shall provide access to agreed amenities as listed in the property listing.</li>
        <li>Either party may terminate with 30 days written notice, subject to local regulations.</li>
        <li>A holding fee may apply upon approval and is credited toward the first month's rent.</li>
    </ol>

    <div class="footer">
        This document was auto-generated by {{ config('app.name') }} Boarding House Finder module.
        Both parties should review and sign a finalized copy before occupancy.
    </div>
</body>
</html>
