<?php

return [
    'name' => 'Universal Business Systems Platform',
    'short_name' => 'UBSP',

    'roles' => [
        'super-admin',
        'administrator',
        'business-owner',
        'manager',
        'staff',
        'student',
        'tenant',
        'customer',
        'landlord',
        'doctor',
        'seller',
        'buyer',
        'guest',
    ],

    'module_owner_permissions' => [
        'boarding-house' => [
            'boarding-house.access',
            'boarding-house.manage-properties',
            'boarding-house.manage-bookings',
        ],
        'clinic' => [
            'clinic.access',
            'clinic.manage-patients',
            'clinic.manage-appointments',
        ],
        'electronics-tracker' => ['electronics-tracker.access'],
        'university-social' => ['university-social.access'],
        'balanced-scorecard' => ['balanced-scorecard.access'],
        'marketplace' => ['marketplace.access'],
        'exchange-tracker' => ['exchange-tracker.access'],
        'weather' => ['weather.access'],
        'monitoring-evaluation' => ['monitoring-evaluation.access'],
        'subscription-sharing' => ['subscription-sharing.access'],
        'sports-league' => ['sports-league.access'],
    ],

    'module_colors' => [
        'module-dot-indigo',
        'module-dot-lavender',
        'module-dot-amber',
        'module-dot-coral',
    ],

    'theme_defaults' => [
        'color_lavender' => '#b8b8d1',
        'color_indigo' => '#5b5f97',
        'color_indigo_dark' => '#4a4d7a',
        'color_amber' => '#ffc145',
        'color_cream' => '#fffffb',
        'color_coral' => '#ff6b6c',
        'color_page_dark' => '#2a2d52',
        'color_surface_dark' => '#45497a',
    ],

    'theme_presets' => [
        'ubsp-classic' => [
            'label' => 'UBSP Classic',
            'color_lavender' => '#b8b8d1',
            'color_indigo' => '#5b5f97',
            'color_indigo_dark' => '#4a4d7a',
            'color_amber' => '#ffc145',
            'color_cream' => '#fffffb',
            'color_coral' => '#ff6b6c',
            'color_page_dark' => '#2a2d52',
            'color_surface_dark' => '#45497a',
        ],
        'ocean' => [
            'label' => 'Ocean Blue',
            'color_lavender' => '#a8c5da',
            'color_indigo' => '#2c5282',
            'color_indigo_dark' => '#1a365d',
            'color_amber' => '#ecc94b',
            'color_cream' => '#f7fafc',
            'color_coral' => '#e53e3e',
            'color_page_dark' => '#1a202c',
            'color_surface_dark' => '#2d3748',
        ],
        'forest' => [
            'label' => 'Forest Green',
            'color_lavender' => '#a7c4a0',
            'color_indigo' => '#2f5233',
            'color_indigo_dark' => '#1b3022',
            'color_amber' => '#d4a017',
            'color_cream' => '#f5f5f0',
            'color_coral' => '#c0392b',
            'color_page_dark' => '#1a2e1a',
            'color_surface_dark' => '#2d4a2d',
        ],
    ],

    'modules' => [
        'electronics-tracker' => [
            'name' => 'Electronics Tracker',
            'description' => 'Track computers, phones, laptops, printers, and accessories.',
            'icon' => 'cpu-chip',
            'color' => 'module-dot-indigo',
            'permission' => 'electronics-tracker.access',
        ],
        'university-social' => [
            'name' => 'University Social',
            'description' => 'Campus social network with posts, events, and messaging.',
            'icon' => 'academic-cap',
            'color' => 'module-dot-lavender',
            'permission' => 'university-social.access',
        ],
        'balanced-scorecard' => [
            'name' => 'Balanced Scorecard',
            'description' => 'Strategic objectives, KPIs, targets, and performance reports.',
            'icon' => 'chart-bar',
            'color' => 'module-dot-amber',
            'permission' => 'balanced-scorecard.access',
        ],
        'marketplace' => [
            'name' => 'Marketplace',
            'description' => 'Buy and sell products with reviews and messaging.',
            'icon' => 'shopping-bag',
            'color' => 'module-dot-coral',
            'permission' => 'marketplace.access',
        ],
        'boarding-house' => [
            'name' => 'Boarding House Finder',
            'description' => 'Find nearby boarding houses with maps and booking.',
            'icon' => 'home-modern',
            'color' => 'module-dot-lavender',
            'permission' => 'boarding-house.access',
        ],
        'exchange-tracker' => [
            'name' => 'Exchange & Commodity Tracker',
            'description' => 'Exchange rates, fuel, food prices, and market trends.',
            'icon' => 'currency-dollar',
            'color' => 'module-dot-amber',
            'permission' => 'exchange-tracker.access',
        ],
        'weather' => [
            'name' => 'Weather Dashboard',
            'description' => 'Forecasts, maps, and city search.',
            'icon' => 'cloud',
            'color' => 'module-dot-indigo',
            'permission' => 'weather.access',
        ],
        'clinic' => [
            'name' => 'Clinic Management',
            'description' => 'Patients, appointments, records, lab, and billing.',
            'icon' => 'heart',
            'color' => 'module-dot-coral',
            'permission' => 'clinic.access',
        ],
        'monitoring-evaluation' => [
            'name' => 'Monitoring & Evaluation',
            'description' => 'Projects, indicators, budgets, and evidence tracking.',
            'icon' => 'clipboard-document-check',
            'color' => 'module-dot-indigo',
            'permission' => 'monitoring-evaluation.access',
        ],
        'subscription-sharing' => [
            'name' => 'Subscription Sharing',
            'description' => 'Shared subscription plans, members, and renewals.',
            'icon' => 'share',
            'color' => 'module-dot-lavender',
            'permission' => 'subscription-sharing.access',
        ],
        'sports-league' => [
            'name' => 'Sports League',
            'description' => 'Leagues, teams, fixtures, standings, and statistics.',
            'icon' => 'trophy',
            'color' => 'module-dot-amber',
            'permission' => 'sports-league.access',
        ],
    ],
];
